### ISSUE TITLE
mod remake request: moxlotus' generate

### ISSUE THREAD

**Issue by xkforce** [CaliforniaDemise/Fixeroo#1]
Link to mod curseforge: https://www.curseforge.com/minecraft/mc-mods/generate
Link to mod github: https://github.com/MoxLotus/Generate
Requested features: control of (weighted) block products of flowing and still water and lava according to y level (range) and biome (array support?)
Wishlist: support for any arbitrary fluid combination

**Comment by unnecessarymb** [comment]
Here's an implementation you can almost straight up copy.
https://github.com/DaedalusGame/Alfinivia/blob/master/src/main/java/alfinivia/handlers/LiquidInteractionHandler.java
Honestly, it could be done in base CraftTweaker or GroovyScript with a bit of translation.

**Comment by xkforce** [comment]
man that mod's code is shockingly simple for what it does

**Comment by CaliforniaDemise** [comment]
Not planned, at least for this mod.
