### ISSUE TITLE
Mod not working with `XP Shower` from OpenBlocks

### ISSUE THREAD

**Issue by Krutoy242** [CaliforniaDemise/Fixeroo#3]
XP clumps does not stack together when showered from XP Shower block. It worked fine with Clumps mod before transition to fixeroo.

There you can see, clumps not combined, only when pushed with a Fan:

https://github.com/user-attachments/assets/be5875a7-89ad-474e-9f1a-f3cd0caf4aba

https://mclo.gs/4nTatYO

**Comment by CaliforniaDemise** [comment]
Yeah. [It's XP Orb](https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/entity/EntityXPOrbNoFly.java#L31) overrides the normal vanilla update method

**Comment by CaliforniaDemise** [comment]
Fixed.
