### ISSUE TITLE
Weird movement behavior on 2.2 update

### ISSUE THREAD

**Issue by ChromaPIE** [CaliforniaDemise/Fixeroo#4]
Player is pushed away by blocks.
Don't know why but the issue seems more noticeable in the Nether, but still seen in the Overworld.

How to reproduce:
Build something like this on the floor where a =air and b = any solid block:
```
a b a
b a b
a b a
```
jump into it and see if it feels like there's something preventing you from walking freely in this 1 block space.

or just walk around in a naturally generated world and feel the strangeness.

Other mentionable stuff that might have involved in this:
I got step-up enabled (step 1 block up without having to jump)
Aqua Acrobatics mod

2.1 doesn't have such issue.

**Comment by CaliforniaDemise** [comment]
Fixed.
