### ISSUE TITLE
Orb clumps get smaller instead of larger (?)

### ISSUE THREAD

**Issue by Krutoy242** [CaliforniaDemise/Fixeroo#6]
Killing monsters that drop lot of XP making orbs TOO BIG.

I think, logarithmic or square root function for size of the orb could be good here. I want my orbs to always grow, without max size. But growth should be not so big on huge values.

![image](https://github.com/user-attachments/assets/2b58c0d9-dcdf-41f1-ad38-7a9fe37917b9)

https://github.com/user-attachments/assets/66d6d26f-7360-4079-807f-782ce92a9934

**Comment by CaliforniaDemise** [comment]
Disable changeOrbSize in configs. It works as intended.

**Comment by Krutoy242** [comment]
Current implementation is wrong.

There I spawned orbs, each one 10 times bigger than previous. You can see that 
- `100,00` same size as `1,000`
- Starting from `100,000` size dropped to zero instead of growing

![image](https://github.com/user-attachments/assets/6b0bd240-c841-4c89-b0db-c18fd23db3f9)

**Comment by CaliforniaDemise** [comment]
Interesting. It's a square root function so it should always get bigger. I will look into it later.

**Comment by Krutoy242** [comment]
Ok, after game reload it working, but......
![image](https://github.com/user-attachments/assets/c9e2ba5d-985f-4c03-a6ee-2dcb4a5e95bf)

1. Make default MC warning that changing `changeOrbSize` config value require to reload the game
2. Isnt those orbs too big?

**Comment by CaliforniaDemise** [comment]
1. I will make it changeable without needing to reload.
2. I don't think someone would make an xp orb that has experience around 100 or 1000 levels in a normal playthrough and even if they do I don't think they would complain about it being big.
